k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: 58949c7b-c5e8-5a59-87e7-73bc4cc80576
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifests
  cluster_info:
    cluster_id: 6064e065-955c-5e6e-a9c8-0dc6f49b7da5
    cluster_name: AES Smoke Tests - Manual Install
